export type Language = 'ko' | 'en';

export const translations = {
  ko: {
    'newGame': '새로하기',
    'continue': '이어하기',
    'settings': '설정',
    'exit': '게임 종료',
    'none': '없음',
    'language': '언어',
    'resolution': '해상도',
    'fullscreen': '전체 화면',
    'back': '뒤로 가기',
    'apply': '적용',
    'cancel': '취소',
    'on': '켜짐',
    'off': '꺼짐',
    'pause': '일시정지',
    'help': '도움말',
    'resume': '재개하기',
    'mainMenu': '메인으로',
    'newGameConfirm': '기존 진행 중인 게임 데이터가 있습니다.\n삭제하고 새로운 게임을 시작하시겠습니까?',
    'deck': '내 덱',
    'selectCharacter': '캐릭터 선택',
    'selectCharacterDesc': '함께할 캐릭터를 선택하세요',
    'startGame': '게임 시작',
    'weaponSwordShield': '칼과 방패',
    'weaponBow': '활',
    'weaponGreatsword': '두손검',
    'weaponHammer': '망치',
    'weaponSpear': '창',
    'statHp': '체력',
    'statDef': '방어',
    'statAtk': '공격',
    'statCrit': '크확',
    'statCritDmg': '크뎀',
    'descGuardian': '쉴드 카드 효율 2배',
    'descRanger': '매 턴 화살 수급 카드 1장 보장\n화살 종류별 랜덤 추가 데미지',
    'descBerserker': '체력이 낮을수록 크리티컬 확률·데미지↑',
    'descTitan': '적의 방어막을 무시하고 파괴',
    'descLancer': '투창 카드 1장 보장\n크리티컬 데미지 ≥ 적 체력 시 즉사',
    'loading': '로딩 중...',
    'cardGallery': '카드 도감',
    'tabAll': '전체',
    'tabWater': '💧 물',
    'tabFire': '🔥 불',
    'tabGrass': '🌿 풀',
    'tabLightning': '⚡ 번개',
    'tabEarth': '🪨 돌',
    'tabNormal': '⚔️ 일반',
    'noGrade': '(등급 없음)',
    'cardAttack': '⚔  공격력',
    'cardDefense': '🛡  방어력',
    'cardCost': '💠  마나 비용',
    'charInfo': '캐릭터 정보',
    'deckList': '현재 덱 리스트',
    'langKorean': '한국어',
    'langEnglish': 'English',
    // ── 카드 이름 ──────────────────────────────────────────────────────────────
    'card0Name': '물의 물약',    'card1Name': '산호 검사',      'card2Name': '폭풍의 기사',
    'card3Name': '포세이돈',     'card4Name': '심해의 대어',
    'card5Name': '작은 불꽃',   'card6Name': '화염 쥐',        'card7Name': '화염포 전사',
    'card8Name': '불사조',       'card9Name': '마왕',
    'card10Name': '새싹 정령',  'card11Name': '식충 식물',     'card12Name': '나무 거인',
    'card13Name': '고목신',      'card14Name': '드리아드',
    'card15Name': '번개 구슬',  'card16Name': '번개 독수리',   'card17Name': '뇌광 닌자',
    'card18Name': '번개 용',     'card19Name': '제우스',
    'card20Name': '돌멩이',     'card21Name': '사막 전갈',     'card22Name': '암석 골렘',
    'card23Name': '드워프 전사', 'card24Name': '대지의 코뿔소',
    'card25Name': '이중 타격',  'card26Name': '철벽 방어',     'card27Name': '암습',
    'card28Name': '속사 연발',   'card29Name': '회복 물약',
    // ── 카드 설명 ──────────────────────────────────────────────────────────────
    'card0Desc': '맑은 샘에서 채운 물약.\n체력을 소량 회복한다.',
    'card1Desc': '산호 검을 든 바다 전사.\n물속에서 더욱 강해진다.',
    'card2Desc': '물의 소용돌이를 두른 기사.\n주위 모든 적에게 피해를 준다.',
    'card3Desc': '바다를 지배하는 신.\n삼지창으로 강렬한 파도를 일으킨다.',
    'card4Desc': '고대 심해에서 잠든 괴수.\n거대한 파도로 전장을 덮친다.',
    'card5Desc': '마음속에서 피어난 작은 불씨.\n적에게 화상을 입힌다.',
    'card6Desc': '꼬리에 불을 달고 다니는 쥐.\n빠르게 움직여 화상을 남긴다.',
    'card7Desc': '화염포를 장착한 기계 전사.\n폭발적인 화염으로 광역 피해를 준다.',
    'card8Desc': '죽어도 다시 살아나는 전설의 새.\n쓰러진 뒤 부활하여 반격한다.',
    'card9Desc': '지옥 불의 군주.\n모든 것을 태우는 업화로 전장을 지배한다.',
    'card10Desc': '갓 태어난 초록 정령.\n주위에 치유 에너지를 퍼뜨린다.',
    'card11Desc': '날카로운 이빨을 가진 식물 몬스터.\n덩굴로 적을 감아 무력화시킨다.',
    'card12Desc': '크리스탈 뿔을 가진 숲의 수호자.\n강인한 몸으로 아군을 지켜낸다.',
    'card13Desc': '수천 년을 산 거대한 나무의 정령.\n뿌리로 대지를 뒤흔들어 적을 쓰러뜨린다.',
    'card14Desc': '꽃과 함께 잠든 숲의 여신.\n강력한 자연 치유로 아군을 소생시킨다.',
    'card15Desc': '정전기를 머금은 신비한 구슬.\n접촉한 적에게 감전을 부여한다.',
    'card16Desc': '폭풍 구름을 가르는 맹금.\n빠른 강하로 번개 공격을 가한다.',
    'card17Desc': '번개처럼 사라지는 그림자.\n순간이동하듯 적의 빈틈을 노린다.',
    'card18Desc': '구름 위를 누비는 번개 용.\n입에서 뿜는 번개로 여러 적을 마비시킨다.',
    'card19Desc': '하늘을 지배하는 신들의 왕.\n번개 볼트로 전장 전체를 초토화시킨다.',
    'card20Desc': '평범해 보이지만 단단한 돌.\n기본적인 방어막을 형성한다.',
    'card21Desc': '독침을 가진 거대 전갈.\n독 공격으로 적을 서서히 약화시킨다.',
    'card22Desc': '대지에서 태어난 거대 바위 골렘.\n강철 같은 몸으로 모든 공격을 튕겨낸다.',
    'card23Desc': '거대한 철퇴를 휘두르는 드워프.\n한 방에 땅을 진동시키는 강타를 날린다.',
    'card24Desc': '산을 짊어진 고대 코뿔소.\n돌진으로 전선을 완전히 무너뜨린다.',
    'card25Desc': '검과 도끼를 동시에 휘두른다.\n두 번의 연속 공격을 가한다.',
    'card26Desc': '단단한 나무 방패를 앞세운다.\n이번 턴 받는 피해를 크게 감소시킨다.',
    'card27Desc': '어둠 속에서 창으로 기습한다.\n방어 중인 적도 꿰뚫는 관통 피해.',
    'card28Desc': '화살통을 비울 기세로 연속 발사.\n3회 공격, 각 공격마다 피해를 준다.',
    'card29Desc': '붉은 액체가 담긴 신비한 물약.\n체력을 대폭 회복하고 독 상태를 해제한다.'
  },
  en: {
    'newGame': 'New Game',
    'continue': 'Continue',
    'settings': 'Settings',
    'exit': 'Exit',
    'none': 'None',
    'language': 'Language',
    'resolution': 'Resolution',
    'fullscreen': 'Fullscreen',
    'back': 'Back',
    'apply': 'Apply',
    'cancel': 'Cancel',
    'on': 'On',
    'off': 'Off',
    'pause': 'Pause',
    'help': 'Help',
    'resume': 'Resume',
    'mainMenu': 'Main Menu',
    'newGameConfirm': 'Existing game data found.\nAre you sure you want to delete it and start a new game?',
    'deck': 'My Deck',
    'selectCharacter': 'Select Character',
    'selectCharacterDesc': 'Choose your companion',
    'startGame': 'Start Game',
    'weaponSwordShield': 'Sword & Shield',
    'weaponBow': 'Bow',
    'weaponGreatsword': 'Greatsword',
    'weaponHammer': 'Hammer',
    'weaponSpear': 'Spear',
    'statHp': 'HP',
    'statDef': 'DEF',
    'statAtk': 'ATK',
    'statCrit': 'CRIT',
    'statCritDmg': 'C.DMG',
    'descGuardian': 'Shield card efficiency ×2',
    'descRanger': 'Guaranteed arrow supply card per turn\nBonus damage by arrow type',
    'descBerserker': 'Lower HP = higher CRIT rate & damage',
    'descTitan': 'Ignores and destroys enemy shields',
    'descLancer': 'Guaranteed javelin card per turn\nInstant kill if CRIT dmg ≥ enemy HP',
    'loading': 'Loading...',
    'cardGallery': 'Card Gallery',
    'tabAll': 'All',
    'tabWater': '💧 Water',
    'tabFire': '🔥 Fire',
    'tabGrass': '🌿 Grass',
    'tabLightning': '⚡ Lightning',
    'tabEarth': '🪨 Earth',
    'tabNormal': '⚔️ Normal',
    'noGrade': '(No Grade)',
    'cardAttack': '⚔  ATK',
    'cardDefense': '🛡  DEF',
    'cardCost': '💠  Mana',
    'charInfo': 'Character Info',
    'deckList': 'Deck List',
    'langKorean': '한국어',
    'langEnglish': 'English',
    // ── 카드 이름 ──────────────────────────────────────────────────────────────
    'card0Name': 'Water Potion',      'card1Name': 'Coral Swordsman',    'card2Name': 'Storm Knight',
    'card3Name': 'Poseidon',          'card4Name': 'Deep Sea Leviathan',
    'card5Name': 'Small Flame',       'card6Name': 'Flame Rat',          'card7Name': 'Flamethrower Warrior',
    'card8Name': 'Phoenix',           'card9Name': 'Demon Lord',
    'card10Name': 'Sprout Spirit',    'card11Name': 'Carnivorous Plant', 'card12Name': 'Tree Giant',
    'card13Name': 'Ancient Tree God', 'card14Name': 'Dryad',
    'card15Name': 'Thunder Orb',      'card16Name': 'Thunder Eagle',     'card17Name': 'Thunder Ninja',
    'card18Name': 'Thunder Dragon',   'card19Name': 'Zeus',
    'card20Name': 'Stone',            'card21Name': 'Desert Scorpion',   'card22Name': 'Rock Golem',
    'card23Name': 'Dwarf Warrior',    'card24Name': 'Earth Rhino',
    'card25Name': 'Double Strike',    'card26Name': 'Iron Wall Defense', 'card27Name': 'Ambush',
    'card28Name': 'Rapid Fire',       'card29Name': 'Healing Potion',
    // ── 카드 설명 ──────────────────────────────────────────────────────────────
    'card0Desc': 'A potion filled from a clear spring.\nRestores a small amount of HP.',
    'card1Desc': 'A sea warrior wielding a coral sword.\nGrows stronger in water.',
    'card2Desc': 'A knight wrapped in a water vortex.\nDeals damage to all nearby enemies.',
    'card3Desc': 'God who rules the sea.\nSummons mighty waves with a trident.',
    'card4Desc': 'An ancient monster slumbering in the deep.\nOverwhelms the battlefield with a massive wave.',
    'card5Desc': 'A small flame kindled from within.\nInflicts burn on enemies.',
    'card6Desc': 'A rat with a flaming tail.\nMoves quickly and leaves burns behind.',
    'card7Desc': 'A mechanical warrior with a flamethrower.\nDeals explosive AoE fire damage.',
    'card8Desc': 'A legendary bird that rises from death.\nRevives after being defeated to strike back.',
    'card9Desc': 'Lord of hellfire.\nDominates the battlefield with all-consuming flames.',
    'card10Desc': 'A newborn green spirit.\nSpreads healing energy to those nearby.',
    'card11Desc': 'A plant monster with sharp teeth.\nEnsnares enemies with vines to immobilize them.',
    'card12Desc': 'A forest guardian with crystal horns.\nProtects allies with its resilient body.',
    'card13Desc': 'Spirit of an ancient tree thousands of years old.\nShakes the earth with roots to fell enemies.',
    'card14Desc': 'A forest goddess sleeping among flowers.\nRevives allies with powerful natural healing.',
    'card15Desc': 'A mysterious orb charged with static electricity.\nInflicts paralysis on enemies it touches.',
    'card16Desc': 'A raptor that cuts through storm clouds.\nDives swiftly to strike with lightning.',
    'card17Desc': 'A shadow that vanishes like lightning.\nTeleports to exploit enemy weak points.',
    'card18Desc': 'A lightning dragon that roams above the clouds.\nParalyzes multiple enemies with lightning breath.',
    'card19Desc': 'King of the gods who rules the sky.\nLays waste to the entire battlefield with lightning bolts.',
    'card20Desc': 'A plain but sturdy rock.\nForms a basic defensive barrier.',
    'card21Desc': 'A giant scorpion with a venomous stinger.\nGradually weakens enemies with poison attacks.',
    'card22Desc': 'A massive rock golem born from the earth.\nDeflects all attacks with its steel-like body.',
    'card23Desc': 'A dwarf wielding a massive iron mace.\nDelivers a ground-shaking blow in a single strike.',
    'card24Desc': 'An ancient rhino carrying mountains on its back.\nCharges to completely shatter the front line.',
    'card25Desc': 'Swings sword and axe simultaneously.\nDelivers two consecutive attacks.',
    'card26Desc': 'Raises a solid wooden shield.\nGreatly reduces damage taken this turn.',
    'card27Desc': 'Strikes from the shadows with a spear.\nDeals piercing damage that bypasses defense.',
    'card28Desc': 'Unleashes a barrage emptying the quiver.\nAttacks 3 times, dealing damage with each hit.',
    'card29Desc': 'A mysterious potion filled with red liquid.\nRestores a large amount of HP and cures poison.'
  }
};

class LocalizationManager {
  private static instance: LocalizationManager;
  private currentLang: Language = 'ko';

  private constructor() {}

  static getInstance() {
    if (!LocalizationManager.instance) {
      LocalizationManager.instance = new LocalizationManager();
    }
    return LocalizationManager.instance;
  }

  setLanguage(lang: Language) {
    this.currentLang = lang;
  }

  getLanguage() {
    return this.currentLang;
  }

  t(key: string): string {
    return (translations[this.currentLang] as any)[key] || key;
  }
}

export const i18n = LocalizationManager.getInstance();
