export type Language = 'ko' | 'en';

export const translations = {
  ko: {
    'newGame': '새로하기',
    'continue': '이어하기',
    'settings': '설정',
    'exit': '게임 종료',
    'none': '없음',
    'language': '언어',
    'resolution': '해상도',
    'fullscreen': '전체 화면',
    'bgmVolume': '배경음',
    'sfxVolume': '효과음',
    'back': '뒤로 가기',
    'apply': '적용',
    'cancel': '취소',
    'on': '켜짐',
    'off': '꺼짐',
    'pause': '일시정지',
    'help': '도움말',
    'resume': '재개하기',
    'mainMenu': '메인으로',
    'newGameConfirm': '기존 진행 중인 게임 데이터가 있습니다.\n삭제하고 새로운 게임을 시작하시겠습니까?',
    'deck': '내 덱',
    'selectCharacter': '캐릭터 선택',
    'selectCharacterDesc': '함께할 캐릭터를 선택하세요',
    'startGame': '게임 시작',
    'weaponSwordShield': '칼과 방패',
    'weaponBow': '활',
    'weaponGreatsword': '두손검',
    'weaponHammer': '망치',
    'weaponSpear': '창',
    'statHp': '체력',
    'statDef': '방어',
    'statAtk': '공격',
    'statCrit': '크확',
    'statCritDmg': '크뎀',
    'descGuardian': '쉴드 카드 효율 2배',
    'descRanger': '화살 카드 = (내 ATK + 카드밸류)\n연쇄 공격 데미지 +50%',
    'descBerserker': 'HP 60% 이하 시 크리티컬 확률·데미지↑',
    'descTitan': '모든 공격이 방어력 무시 (관통)',
    'descLancer': '투창 카드 항상 크리티컬\n크리뎀 × 투창밸류 ≥ 적 HP → 즉사',
    'charHintGuardian': '[ 칼과 방패 ]\n추천 속성: 흙 · 물\n\n방어막 카드가 2배 효율.\n수비→흙/물 공격 패턴으로 안정적 생존.\nDEF가 높아 적 피해를 크게 줄임.\n\n초보자 추천 캐릭터',
    'charHintRanger': '[ 활 ]\n추천 속성: 번개 · 풀\n\n화살 데미지 = 내 ATK + 카드밸류.\nATK 강화할수록 화살이 강해짐.\n상태이상 후 연쇄(chain) 폭딜 전략.\n\nATK 성장형 | 고위험 고수익',
    'charHintBerserker': '[ 두손검 ]\n추천 속성: 불 · 번개\n\nHP 60% 이하 시 크리 +20%, 크리뎀 +0.3.\nHP를 적당히 낮게 유지하는 게 핵심.\nDEF 10으로 버티면서 크리 극대화.\n\n중급자 추천 | 공격형',
    'charHintTitan': '[ 망치 ]\n추천 속성: 흙 · 불\n\n모든 공격이 방어력 무시 (관통).\n방어막 두꺼운 보스에게 최강.\nHP 115로 생존력 높음.\nDEF가 없어 받는 피해는 큼.\n\n딜탱 | 초보자 추천',
    'charHintLancer': '[ 창 ]\n추천 속성: 물 · 풀\n\n투창 카드 = 항상 크리티컬.\n크리뎀(1.8) × 투창밸류 ≥ 적 HP → 즉사.\n★ 높은 투창 카드가 핵심 자원.\nDEF 0, HP 80 → 빠른 결판 필요.\n\n고급자 추천 | 순간폭딜',
    'loading': '로딩 중...',
    'cardGallery': '카드 도감',
    'tabAll': '전체',
    'tabWater': '💧 물',
    'tabFire': '🔥 불',
    'tabGrass': '🌿 풀',
    'tabLightning': '⚡ 번개',
    'tabEarth': '⛰ 돌',
    'tabNormal': '⚔ 일반',
    'noGrade': '(등급 없음)',
    'cardAttack': '⚔  공격력',
    'cardDefense': '🛡  방어력',
    'cardCost': '💠  마나 비용',
    'charInfo': '캐릭터 정보',
    'deckList': '현재 덱 리스트',
    'langKorean': '한국어',
    'langEnglish': 'English',
    // ── 공통 버튼 ──────────────────────────────────────────────────────────────
    'confirm': '확인',
    'skip': '그냥 지나침',
    'receive': '받기',
    'flipCard': '뒤집기',
    'continueBtn': '계속',
    'skipGold': '그냥 지나침  (+10G)',
    'cancelGold': '취소  (+10G)',
    'exitWithGold': '10G 받고 나가기',
    'bossStartFight': '전투 시작',
    // ── 속성 이름 ──────────────────────────────────────────────────────────────
    'elemWater': '물',
    'elemFire': '불',
    'elemGrass': '풀',
    'elemLightning': '번개',
    'elemEarth': '땅',
    'elemNormal': '무속성',
    // ── 전투 이벤트 ────────────────────────────────────────────────────────────
    'battleTitleElemental': '[{elem}] 속성 몬스터 출현!',
    'battleTitleNormal': '무속성 몬스터 출현!',
    'battleDescElemental': '현재 맵 속성({elem}) 몬스터와 전투합니다.\n속성 유불리에 따라 데미지가 달라집니다.',
    'battleDescNormal': '일반 속성 몬스터와 전투합니다.',
    // ── 일반 몬스터 이름 ───────────────────────────────────────────────────────
    'mobGoblin': '고블린',     'mobSkeleton': '스켈레톤',  'mobSlime': '슬라임',
    'mobZombie': '좀비',       'mobBat': '배트',           'mobRat': '쥐떼',
    'mobPoison': '독충',       'mobUnknown': '정체불명의 몬스터',
    // ── 속성 몬스터 이름 ───────────────────────────────────────────────────────
    'mobWaterSpirit': '물의 정령',     'mobJellyfishMage': '해파리 마법사', 'mobIceKnight': '얼음 기사',
    'mobFireSpirit': '화염 정령',      'mobMagmaGolem': '마그마 골렘',      'mobFlameDemon': '불꽃 도깨비',
    'mobGrassSpirit': '숲의 정령',     'mobPoisonWitch': '독초 마녀',       'mobVineGolem': '덩굴 골렘',
    'mobLightningSpirit': '번개 정령', 'mobElectricBat': '전기 박쥐',       'mobStormMage': '폭풍 마도사',
    'mobEarthSpirit': '땅의 정령',     'mobRockGiant': '바위 거인',          'mobSandWarrior': '모래 무사',
    // ── 강화 이벤트 ────────────────────────────────────────────────────────────
    'enhanceTitle': '패시브 강화',
    'enhanceDesc': '하나를 선택하여 영구 강화합니다.\n또는 10G를 받고 지나칩니다.',
    'passiveIronWill': '강철 의지',
    'passiveIronWillDesc': '최대 HP +10  (현재 {cur} → {next})',
    'passiveSharpSense': '예리한 감각',
    'passiveSharpSenseDesc': '치명 확률 +5%  (현재 {cur}% → {next}%)',
    'passiveBattleFrenzy': '전투 광기',
    'passiveBattleFrenzyDesc': '치명 배율 +0.2×  (현재 {cur}× → {next}×)',
    'passiveIronWall': '철벽 방어',
    'passiveIronWallDesc': '방어력 +3  (현재 {cur} → {next})',
    'passiveSharpInstinct': '날카로운 본능',
    'passiveSharpInstinctDesc': '공격력 +5  (현재 {cur} → {next})',
    // ── 보물 이벤트 ────────────────────────────────────────────────────────────
    'treasureTitle': '보물 상자',
    'treasureSlot': '장비 칸: {cur} / {max}',
    'treasureDescFull': '장비 칸이 가득 찼습니다.\n획득 시 기존 장비 중 하나와 교체합니다.',
    'treasureDescNormal': '장비 3개 중 1개를 선택합니다.\n또는 10G를 받고 지나칩니다.',
    'treasureReplaceTitle': '교체할 장비를 선택하세요',
    // ── 하트 카드 이벤트 ───────────────────────────────────────────────────────
    'heartTitle': '하트 카드',
    'heartDesc': 'HP를 5 잃는 대신\n덱의 카드 밸류를 ×1.3 영구 강화합니다.\n\n현재 HP: {hp}',
    'heartWarning': 'HP가 부족합니다! (HP > 5 필요)',
    'heartAccept': '수락  (HP -5)',
    'heartRefuse': '거절',
    // ── 방어 카드 이벤트 ───────────────────────────────────────────────────────
    'shieldTitle': '방어 카드',
    'shieldDesc': '덱의 모든 방어(쉴드) 카드의\n쉴드량이 ×1.2 영구 증가합니다.',
    // ── 별 카드 이벤트 ─────────────────────────────────────────────────────────
    'starTitle': '별 카드',
    'starDesc': '선택한 속성의 카드 중 하나의 별(등급)을 +1 올립니다.',
    // ── 대체 카드 이벤트 ───────────────────────────────────────────────────────
    'swapTitle': '대체 카드',
    'swapDesc': '교환할 속성을 선택합니다.\n선택한 속성 카드 → 다른 속성 카드로 교환',
    'swapResultTitle': '속성 교환 완료',
    // ── 카드 도박 이벤트 ───────────────────────────────────────────────────────
    'flipTitle': '카드 도박',
    'flipRuleText': '같은 속성이면 골드 ×2, 다른 속성이면 즉시 종료 0G\n언제든 10G 받고 나갈 수 있습니다.',
    // ── 인디언 포커 이벤트 ─────────────────────────────────────────────────────
    'indianPokerTitle': '인디언 포커  ({elem} 속성)',
    // ── 보스 이벤트 ────────────────────────────────────────────────────────────
    'bossAppear': '{elem} 보스 등장',
    'bossNameWater': '해룡왕  아쿠아리스',
    'bossNameFire': '화염군주  이그니스',
    'bossNameGrass': '대수목  실바나',
    'bossNameLightning': '뇌신  토르무스',
    'bossNameEarth': '대지의 왕  테라',
    'bossNameFinal': '혼돈의 군주  카오스',
    // ── 인트로 ─────────────────────────────────────────────────────────────────
    'totalGold': '누적 골드',
    'collectedEquip': '수집 장비',
    'noEquipYet': '아직 없음',
    // ── 패시브 강화 ────────────────────────────────────────────────────────────
    'passiveUpgrade': '영구 강화',
    'passiveUpgradeTitle': '영구 강화  —  골드를 소비하여 모든 런에 적용되는 능력치를 강화합니다',
    'yourGold': '보유 골드',
    'upgradeMaxHp': '최대 HP +10',
    'upgradeAtk': '공격력 +1',
    'upgradeDef': '방어력 +1',
    'upgradeCrit': '치명타 확률 +2%',
    'upgradeCardMult': '카드 배율 +5%',
    'upgradeEquipSlot': '장비 슬롯 +1',
    'upgradeLevel': 'Lv',
    'upgradeMaxed': '최대',
    'upgradeBuy': '강화',
    'upgradeNotEnoughGold': '골드 부족',
    // ── 캐릭터 선택 ────────────────────────────────────────────────────────────
    'startEquip': '출발 장비',
    'noEquipCollected': '수집된 장비 없음  —  플레이를 통해 장비를 모아보세요',
    // ── 장비 이벤트 ────────────────────────────────────────────────────────────
    'newEquip': '새 장비',
    'noNewEquip': '보물 상자에 새 장비가 없습니다.\n(이미 모든 장비를 보유 중)',
    // ── 카드 도박 이벤트 ───────────────────────────────────────────────────────
    'currentGoldLabel': '현재 골드',
    'flipFirstCard': '첫 번째 카드를 뒤집습니다...',
    'baseAttrLabel': '기준 속성',
    'sameAttr': '같은 속성! {gold}G',
    'diffAttr': '다른 속성! 골드 0G',
    'allFlipped': '완주! 최종 골드: {gold}G',
    // ── 인디언 포커 이벤트 ─────────────────────────────────────────────────────
    'round': '라운드',
    'foldToken': '포기 토큰',
    'remainChance': '남은 기회',
    'opponent': '상대방',
    'myCardHidden': '나 (뒤집힘)',
    'myCardRevealed': '나',
    'betOrFold': '배팅 또는 배팅 포기를 선택하세요.',
    'obtainableCard': '확보 가능 카드',
    'bet': '배팅',
    'pokerFold': '배팅 포기',
    'noFoldToken': '배팅 포기 토큰 없음!',
    'cardReveal': '카드 공개!',
    'pokerWin': '승리! ★{n} 카드 확보 가능',
    'pokerDraw': '동점! 라운드 재시작',
    'pokerLose': '패배! 기회 {n}개 남음',
    'pokerExhausted': '기회 소진. 이벤트 종료',
    'pokerSweep': '전승! ★{n}성 카드 획득!',
    'pokerFiveStarFold': '5성 카드를 포기할 수 없습니다!',
    'pokerFolded': '포기 (토큰 {n}개 남음)',
    'pokerTakeConfirm': '★{n}성 카드를 받고 끝내시겠습니까?',
    // ── 보스 이벤트 ────────────────────────────────────────────────────────────
    'bossRoundInfo': '{rounds}라운드 전투\n보스를 쓰러뜨리면 고유 보상을 획득합니다.',
    'bossStats': 'HP {hp}/{maxHp}   공격 {atk}   방어 {def}   치명 {crit}%',
    // ── 카드 이름 ──────────────────────────────────────────────────────────────
    'card0Name': '물의 물약',    'card1Name': '산호 검사',      'card2Name': '폭풍의 기사',
    'card3Name': '포세이돈',     'card4Name': '심해의 대어',
    'card5Name': '작은 불꽃',   'card6Name': '화염 쥐',        'card7Name': '화염포 전사',
    'card8Name': '불사조',       'card9Name': '마왕',
    'card10Name': '새싹 정령',  'card11Name': '식충 식물',     'card12Name': '나무 거인',
    'card13Name': '고목신',      'card14Name': '드리아드',
    'card15Name': '번개 구슬',  'card16Name': '번개 독수리',   'card17Name': '뇌광 닌자',
    'card18Name': '번개 용',     'card19Name': '제우스',
    'card20Name': '돌멩이',     'card21Name': '사막 전갈',     'card22Name': '암석 골렘',
    'card23Name': '드워프 전사', 'card24Name': '대지의 코뿔소',
    'card25Name': '이중 타격',  'card26Name': '철벽 방어',     'card27Name': '암습',
    'card28Name': '속사 연발',   'card29Name': '회복 물약',
    // ── 카드 설명 ──────────────────────────────────────────────────────────────
    'card0Desc': '맑은 샘에서 채운 물약.\n물 속성으로 공격한다.',
    'card1Desc': '산호 검을 든 바다 전사.\n물 속성으로 공격한다.',
    'card2Desc': '물의 소용돌이를 두른 기사.\n물 속성으로 공격한다.',
    'card3Desc': '바다를 지배하는 신.\n물 속성으로 공격한다.',
    'card4Desc': '고대 심해에서 잠든 괴수.\n물 속성으로 공격한다.',
    'card5Desc': '마음속에서 피어난 작은 불씨.\n불 속성으로 공격한다.',
    'card6Desc': '꼬리에 불을 달고 다니는 쥐.\n불 속성으로 공격한다.',
    'card7Desc': '화염포를 장착한 기계 전사.\n불 속성으로 공격한다.',
    'card8Desc': '죽어도 다시 살아나는 전설의 새.\n불 속성으로 공격한다.',
    'card9Desc': '지옥 불의 군주.\n불 속성으로 공격한다.',
    'card10Desc': '갓 태어난 초록 정령.\n풀 속성으로 공격한다.',
    'card11Desc': '날카로운 이빨을 가진 식물 몬스터.\n풀 속성으로 공격한다.',
    'card12Desc': '크리스탈 뿔을 가진 숲의 수호자.\n풀 속성으로 공격한다.',
    'card13Desc': '수천 년을 산 거대한 나무의 정령.\n풀 속성으로 공격한다.',
    'card14Desc': '꽃과 함께 잠든 숲의 여신.\n풀 속성으로 공격한다.',
    'card15Desc': '정전기를 머금은 신비한 구슬.\n번개 속성으로 공격한다.',
    'card16Desc': '폭풍 구름을 가르는 맹금.\n번개 속성으로 공격한다.',
    'card17Desc': '번개처럼 사라지는 그림자.\n번개 속성으로 공격한다.',
    'card18Desc': '구름 위를 누비는 번개 용.\n번개 속성으로 공격한다.',
    'card19Desc': '하늘을 지배하는 신들의 왕.\n번개 속성으로 공격한다.',
    'card20Desc': '평범해 보이지만 단단한 돌.\n땅 속성으로 공격한다.',
    'card21Desc': '독침을 가진 거대 전갈.\n땅 속성으로 공격한다.',
    'card22Desc': '대지에서 태어난 거대 바위 골렘.\n땅 속성으로 공격한다.',
    'card23Desc': '거대한 철퇴를 휘두르는 드워프.\n땅 속성으로 공격한다.',
    'card24Desc': '산을 짊어진 고대 코뿔소.\n땅 속성으로 공격한다.',
    'card25Desc': '무기에 따른 공격을 한다.',
    'card26Desc': '방어막이 생성된다.\n상대 턴에 받는 데미지를 상쇄한다.',
    'card27Desc': '(창 전용)창을 던진다.\n적의 피보다 치명타 데미지가 높으면 즉사시킨다.',
    'card28Desc': '(활 전용) 화살로 공격한다.\n레인저가 사용하면 데미지 2배.',
    'card29Desc': '붉은 액체가 담긴 신비한 물약.\n체력을 회복한다.'
  },
  en: {
    'newGame': 'New Game',
    'continue': 'Continue',
    'settings': 'Settings',
    'exit': 'Exit',
    'none': 'None',
    'language': 'Language',
    'resolution': 'Resolution',
    'fullscreen': 'Fullscreen',
    'bgmVolume': 'BGM Volume',
    'sfxVolume': 'SFX Volume',
    'back': 'Back',
    'apply': 'Apply',
    'cancel': 'Cancel',
    'on': 'On',
    'off': 'Off',
    'pause': 'Pause',
    'help': 'Help',
    'resume': 'Resume',
    'mainMenu': 'Main Menu',
    'newGameConfirm': 'Existing game data found.\nAre you sure you want to delete it and start a new game?',
    'deck': 'My Deck',
    'selectCharacter': 'Select Character',
    'selectCharacterDesc': 'Choose your companion',
    'startGame': 'Start Game',
    'weaponSwordShield': 'Sword & Shield',
    'weaponBow': 'Bow',
    'weaponGreatsword': 'Greatsword',
    'weaponHammer': 'Hammer',
    'weaponSpear': 'Spear',
    'statHp': 'HP',
    'statDef': 'DEF',
    'statAtk': 'ATK',
    'statCrit': 'CRIT',
    'statCritDmg': 'C.DMG',
    'descGuardian': 'Shield card efficiency ×2',
    'descRanger': 'Arrow dmg = (ATK + card value)\nChain attack damage +50%',
    'descBerserker': 'HP below 60% → CRIT rate & damage↑',
    'descTitan': 'All attacks pierce enemy defense',
    'descLancer': 'Javelin card always crits\nC.DMG × javelin value ≥ enemy HP → instant kill',
    'charHintGuardian': '[ Sword & Shield ]\nRecommended: Earth · Water\n\nShield cards are 2× effective.\nDefend → Earth/Water attack pattern.\nHigh DEF reduces incoming damage.\n\nRecommended for beginners',
    'charHintRanger': '[ Bow ]\nRecommended: Lightning · Grass\n\nArrow dmg = ATK + card value.\nStronger as ATK increases.\nSetup status → chain burst strategy.\n\nATK Scaling | High Risk High Reward',
    'charHintBerserker': '[ Greatsword ]\nRecommended: Fire · Lightning\n\nBelow 60% HP: CRIT +20%, C.DMG +0.3.\nKey skill: keep HP in the danger zone.\nDEF 10 helps survive long enough.\n\nIntermediate | Offensive',
    'charHintTitan': '[ Hammer ]\nRecommended: Earth · Fire\n\nAll attacks ignore enemy defense.\nBest against high-armor bosses.\nHP 115 for strong survivability.\nNo DEF — takes full enemy damage.\n\nTank-DPS | Beginner Friendly',
    'charHintLancer': '[ Spear ]\nRecommended: Water · Grass\n\nJavelin card always crits.\nC.DMG (×1.8) × value ≥ enemy HP → instant kill.\nHigh-star javelin cards are key.\nNo DEF, HP 80 — end fights fast.\n\nAdvanced | Burst Damage',
    'loading': 'Loading...',
    'cardGallery': 'Card Gallery',
    'tabAll': 'All',
    'tabWater': '💧 Water',
    'tabFire': '🔥 Fire',
    'tabGrass': '🌿 Grass',
    'tabLightning': '⚡ Lightning',
    'tabEarth': '⛰ Earth',
    'tabNormal': '⚔ Normal',
    'noGrade': '(No Grade)',
    'cardAttack': '⚔  ATK',
    'cardDefense': '🛡  DEF',
    'cardCost': '💠  Mana',
    'charInfo': 'Character Info',
    'deckList': 'Deck List',
    'langKorean': '한국어',
    'langEnglish': 'English',
    // ── 공통 버튼 ──────────────────────────────────────────────────────────────
    'confirm': 'OK',
    'skip': 'Skip',
    'receive': 'Take',
    // ── 속성 이름 ──────────────────────────────────────────────────────────────
    'elemWater': 'Water',
    'elemFire': 'Fire',
    'elemGrass': 'Grass',
    'elemLightning': 'Lightning',
    'elemEarth': 'Earth',
    'elemNormal': 'Normal',
    // ── 전투 이벤트 ────────────────────────────────────────────────────────────
    'battleTitleElemental': '[{elem}] Elemental Monster Appears!',
    'battleTitleNormal': 'Normal Monster Appears!',
    'battleDescElemental': 'Battle a {elem} elemental monster.\nDamage varies based on elemental advantage.',
    'battleDescNormal': 'Battle against a normal monster.',
    // ── 일반 몬스터 이름 ───────────────────────────────────────────────────────
    'mobGoblin': 'Goblin',        'mobSkeleton': 'Skeleton',  'mobSlime': 'Slime',
    'mobZombie': 'Zombie',        'mobBat': 'Bat',            'mobRat': 'Rat Pack',
    'mobPoison': 'Venomling',     'mobUnknown': 'Unknown Monster',
    // ── 속성 몬스터 이름 ───────────────────────────────────────────────────────
    'mobWaterSpirit': 'Water Spirit',      'mobJellyfishMage': 'Jellyfish Mage',  'mobIceKnight': 'Ice Knight',
    'mobFireSpirit': 'Fire Spirit',        'mobMagmaGolem': 'Magma Golem',        'mobFlameDemon': 'Flame Imp',
    'mobGrassSpirit': 'Forest Spirit',     'mobPoisonWitch': 'Poison Witch',      'mobVineGolem': 'Vine Golem',
    'mobLightningSpirit': 'Storm Spirit',  'mobElectricBat': 'Electric Bat',      'mobStormMage': 'Storm Mage',
    'mobEarthSpirit': 'Earth Spirit',      'mobRockGiant': 'Rock Giant',          'mobSandWarrior': 'Sand Warrior',
    // ── 강화 이벤트 ────────────────────────────────────────────────────────────
    'enhanceTitle': 'Passive Upgrade',
    'enhanceDesc': 'Choose one for a permanent upgrade.\nOr take 10G and skip.',
    'passiveIronWill': 'Iron Will',
    'passiveIronWillDesc': 'Max HP +10  ({cur} → {next})',
    'passiveSharpSense': 'Sharp Sense',
    'passiveSharpSenseDesc': 'CRIT Rate +5%  ({cur}% → {next}%)',
    'passiveBattleFrenzy': 'Battle Frenzy',
    'passiveBattleFrenzyDesc': 'CRIT DMG +0.2×  ({cur}× → {next}×)',
    'passiveIronWall': 'Iron Wall',
    'passiveIronWallDesc': 'DEF +3  ({cur} → {next})',
    'passiveSharpInstinct': 'Sharp Instinct',
    'passiveSharpInstinctDesc': 'ATK +5  ({cur} → {next})',
    // ── 보물 이벤트 ────────────────────────────────────────────────────────────
    'treasureTitle': 'Treasure Chest',
    'treasureSlot': 'Equipment Slots: {cur} / {max}',
    'treasureDescFull': 'Equipment slots are full.\nYou must replace an existing item.',
    'treasureDescNormal': 'Choose 1 of 3 equipment items.\nOr take 10G and skip.',
    'treasureReplaceTitle': 'Select equipment to replace',
    // ── 하트 카드 이벤트 ───────────────────────────────────────────────────────
    'heartTitle': 'Heart Card',
    'heartDesc': 'Lose 5 HP in exchange for\npermanently boosting card value by ×1.3.\n\nCurrent HP: {hp}',
    'heartWarning': 'Not enough HP! (Need HP > 5)',
    'heartAccept': 'Accept  (HP -5)',
    'heartRefuse': 'Refuse',
    // ── 방어 카드 이벤트 ───────────────────────────────────────────────────────
    'shieldTitle': 'Defense Card',
    'shieldDesc': 'Permanently increases the shield\nvalue of all defense cards by ×1.2.',
    // ── 별 카드 이벤트 ─────────────────────────────────────────────────────────
    'starTitle': 'Star Card',
    'starDesc': 'Upgrades the star rating of one card\nof the selected element by +1.',
    // ── 대체 카드 이벤트 ───────────────────────────────────────────────────────
    'swapTitle': 'Swap Card',
    'swapDesc': 'Select the element to swap.\nCards of that element will be exchanged for another element.',
    'swapResultTitle': 'Element Swapped',
    // ── 카드 도박 이벤트 ───────────────────────────────────────────────────────
    'flipTitle': 'Card Gamble',
    'flipRuleText': 'Same element: Gold ×2, Different: 0G immediately\nYou can leave with 10G at any time.',
    // ── 인디언 포커 이벤트 ─────────────────────────────────────────────────────
    'indianPokerTitle': 'Indian Poker  ({elem})',
    // ── 보스 이벤트 ────────────────────────────────────────────────────────────
    'bossAppear': '{elem} Boss Appears',
    'bossNameWater': 'Sea Dragon King  Aquaris',
    'bossNameFire': 'Flame Lord  Ignis',
    'bossNameGrass': 'Great Tree  Silvana',
    'bossNameLightning': 'Thunder God  Thormus',
    'bossNameEarth': 'King of Earth  Terra',
    'bossNameFinal': 'Lord of Chaos  Kaos',
    'flipCard': 'Flip',
    'continueBtn': 'Continue',
    'skipGold': 'Skip  (+10G)',
    'cancelGold': 'Cancel  (+10G)',
    'exitWithGold': 'Take 10G and leave',
    'bossStartFight': 'Start Battle',
    // ── 인트로 ─────────────────────────────────────────────────────────────────
    'totalGold': 'Total Gold',
    'collectedEquip': 'Equipment',
    'noEquipYet': 'None yet',
    // ── 패시브 강화 ────────────────────────────────────────────────────────────
    'passiveUpgrade': 'Permanent Upgrades',
    'passiveUpgradeTitle': 'Permanent Upgrades  —  Spend gold to boost stats across all runs',
    'yourGold': 'Your Gold',
    'upgradeMaxHp': 'Max HP +10',
    'upgradeAtk': 'Attack +1',
    'upgradeDef': 'Defense +1',
    'upgradeCrit': 'Crit Chance +2%',
    'upgradeCardMult': 'Card Value +5%',
    'upgradeEquipSlot': 'Equipment Slot +1',
    'upgradeLevel': 'Lv',
    'upgradeMaxed': 'MAX',
    'upgradeBuy': 'Upgrade',
    'upgradeNotEnoughGold': 'Not enough gold',
    // ── 캐릭터 선택 ────────────────────────────────────────────────────────────
    'startEquip': 'Starting Equipment',
    'noEquipCollected': 'No equipment yet  —  Play to collect equipment',
    // ── 장비 이벤트 ────────────────────────────────────────────────────────────
    'newEquip': 'New Equipment',
    'noNewEquip': 'No new equipment in the chest.\n(You already own all equipment)',
    // ── 카드 도박 이벤트 ───────────────────────────────────────────────────────
    'currentGoldLabel': 'Current Gold',
    'flipFirstCard': 'Flipping the first card...',
    'baseAttrLabel': 'Base element',
    'sameAttr': 'Same element! {gold}G',
    'diffAttr': 'Different element! 0G',
    'allFlipped': 'All cleared! Final gold: {gold}G',
    // ── 인디언 포커 이벤트 ─────────────────────────────────────────────────────
    'round': 'Round',
    'foldToken': 'Fold Token',
    'remainChance': 'Remaining Chances',
    'opponent': 'Opponent',
    'myCardHidden': 'Me (hidden)',
    'myCardRevealed': 'Me',
    'betOrFold': 'Choose to bet or fold.',
    'obtainableCard': 'Obtainable Card',
    'bet': 'Bet',
    'pokerFold': 'Fold',
    'noFoldToken': 'No fold tokens!',
    'cardReveal': 'Card revealed!',
    'pokerWin': 'Win! ★{n} card(s) obtainable',
    'pokerDraw': 'Draw! Restarting round.',
    'pokerLose': 'Defeat! {n} chance(s) remaining',
    'pokerExhausted': 'All chances used. Event ended.',
    'pokerSweep': 'Perfect! ★{n}-star card acquired!',
    'pokerFiveStarFold': 'Cannot fold a 5-star card!',
    'pokerFolded': 'Folded ({n} token(s) remaining)',
    'pokerTakeConfirm': 'Take ★{n}-star card and finish?',
    // ── 보스 이벤트 ────────────────────────────────────────────────────────────
    'bossRoundInfo': '{rounds}-round battle\nDefeat the boss for a unique reward.',
    'bossStats': 'HP {hp}/{maxHp}   ATK {atk}   DEF {def}   CRIT {crit}%',
    // ── 카드 이름 ──────────────────────────────────────────────────────────────
    'card0Name': 'Water Potion',      'card1Name': 'Coral Swordsman',    'card2Name': 'Storm Knight',
    'card3Name': 'Poseidon',          'card4Name': 'Deep Sea Leviathan',
    'card5Name': 'Small Flame',       'card6Name': 'Flame Rat',          'card7Name': 'Flamethrower Warrior',
    'card8Name': 'Phoenix',           'card9Name': 'Demon Lord',
    'card10Name': 'Sprout Spirit',    'card11Name': 'Carnivorous Plant', 'card12Name': 'Tree Giant',
    'card13Name': 'Ancient Tree God', 'card14Name': 'Dryad',
    'card15Name': 'Thunder Orb',      'card16Name': 'Thunder Eagle',     'card17Name': 'Thunder Ninja',
    'card18Name': 'Thunder Dragon',   'card19Name': 'Zeus',
    'card20Name': 'Stone',            'card21Name': 'Desert Scorpion',   'card22Name': 'Rock Golem',
    'card23Name': 'Dwarf Warrior',    'card24Name': 'Earth Rhino',
    'card25Name': 'Double Strike',    'card26Name': 'Iron Wall Defense', 'card27Name': 'Ambush',
    'card28Name': 'Rapid Fire',       'card29Name': 'Healing Potion',
    // ── 카드 설명 ──────────────────────────────────────────────────────────────
    'card0Desc': 'A potion filled from a clear spring.\nDeals water damage.',
    'card1Desc': 'A sea warrior wielding a coral sword.\nDeals water damage.',
    'card2Desc': 'A knight wrapped in a water vortex.\nDeals water damage.',
    'card3Desc': 'God who rules the sea.\nDeals water damage.',
    'card4Desc': 'An ancient monster slumbering in the deep.\nDeals water damage.',
    'card5Desc': 'A small flame kindled from within.\nDeals fire damage.',
    'card6Desc': 'A rat with a flaming tail.\nDeals fire damage.',
    'card7Desc': 'A mechanical warrior with a flamethrower.\nDeals fire damage.',
    'card8Desc': 'A legendary bird that rises from death.\nDeals fire damage.',
    'card9Desc': 'Lord of hellfire.\nDeals fire damage.',
    'card10Desc': 'A newborn green spirit.\nDeals grass damage.',
    'card11Desc': 'A plant monster with sharp teeth.\nDeals grass damage.',
    'card12Desc': 'A forest guardian with crystal horns.\nDeals grass damage.',
    'card13Desc': 'Spirit of an ancient tree thousands of years old.\nDeals grass damage.',
    'card14Desc': 'A forest goddess sleeping among flowers.\nDeals grass damage.',
    'card15Desc': 'A mysterious orb charged with static electricity.\nDeals lightning damage.',
    'card16Desc': 'A raptor that cuts through storm clouds.\nDeals lightning damage.',
    'card17Desc': 'A shadow that vanishes like lightning.\nDeals lightning damage.',
    'card18Desc': 'A lightning dragon that roams above the clouds.\nDeals lightning damage.',
    'card19Desc': 'King of the gods who rules the sky.\nDeals lightning damage.',
    'card20Desc': 'A plain but sturdy rock.\nDeals earth damage.',
    'card21Desc': 'A giant scorpion with a venomous stinger.\nDeals earth damage.',
    'card22Desc': 'A massive rock golem born from the earth.\nDeals earth damage.',
    'card23Desc': 'A dwarf wielding a massive iron mace.\nDeals earth damage.',
    'card24Desc': 'An ancient rhino carrying mountains on its back.\nDeals earth damage.',
    'card25Desc': 'Attack with weapons',
    'card26Desc': "Defence is created.\nIt offsets the damage you receive on your opponen's turn",
    'card27Desc': 'Throw a spear (Lancer only).\nInstant kill if Critical Damage \u2265 Enemy HP.',
    'card28Desc': '(Bow only) Take arrows from your quiver.\nDeals double damage when used by a Ranger.',
    'card29Desc': 'A mysterious red liquid.\nRestores HP.'
  }
};

class LocalizationManager {
  private static instance: LocalizationManager;
  private currentLang: Language = 'ko';

  private constructor() {}

  static getInstance() {
    if (!LocalizationManager.instance) {
      LocalizationManager.instance = new LocalizationManager();
    }
    return LocalizationManager.instance;
  }

  setLanguage(lang: Language) {
    this.currentLang = lang;
  }

  getLanguage() {
    return this.currentLang;
  }

  t(key: string): string {
    return (translations[this.currentLang] as any)[key] || key;
  }

  /** {placeholder} 치환을 지원하는 포맷 헬퍼 */
  f(key: string, params: Record<string, string | number>): string {
    let str = this.t(key);
    for (const [k, v] of Object.entries(params)) {
      str = str.replace(`{${k}}`, String(v));
    }
    return str;
  }
}

export const i18n = LocalizationManager.getInstance();
